#################################
# RPM-specific Makefile		#
# http://yum.postgresql.org	#
#				#
# devrim@gunduz.org		#
#################################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.rhel5
SPECFILE="pgrouting2.spec"

# Now, include global Makefile
include ../../../common/Makefile.global
