#################################
# RPM-specific Makefile		#
# https://yum.postgresql.org	#
#                         	#
# Devrim Gunduz			#
# devrim@gunduz.org		#
#################################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.rhel7
SPECFILE="postgresql-9.2.spec"
HOMEDIR=$HOMEDIR

# Now, include global Makefile
include ../../../common/Makefile.global
