#################################
# RPM-specific Makefile		#
# https://yum.postgresql.org	#
#				#
# Devrim Gunduz			#
# devrim@gunduz.org		#
#################################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.f24
SPECFILE="pgdg-fedora-94.spec"

# Now, include global Makefile
include ../../../common/Makefile.global
