#########################################################################
#                                                                       #
#    Dockerfile for Fedora PostgreSQL Spin, with PGDG packages.		#
#            Devrim GUNDUZ <devrim@gunduz.org>                          #
#                                                                       #
#########################################################################

FROM fedora
MAINTAINER devrim@gunduz.org

# Add the PostgreSQL PGP key to verify the official yum repository packages
RUN rpm --import http://yum.postgresql.org/RPM-GPG-KEY-PGDG-94

# Add PostgreSQL's repository. It contains the most recent stable release
# of PostgreSQL, ``9.4``.
RUN rpm -ivh http://yum.postgresql.org/9.4/fedora/fedora-21-x86_64/pgdg-fedora94-9.4-2.noarch.rpm

# Update the Fedora and PostgreSQL repository metadata
RUN yum update -y

# Install PostgreSQL 9.4
RUN yum -y install postgresql94-server postgresql94-contrib

# initdb PostgreSQL 9.4:
CMD	/usr/pgsql-9.4/bin/postgresql94-setup initdb

# Adjust PostgreSQL configuration so that remote connections to the
# database are possible. 
RUN echo "host all  all    0.0.0.0/0  md5" >> /var/lib/pgsql/9.4/data/pg_hba.conf

# And add ``listen_addresses`` to ``/var/lib/pgsql/9.4/data/postgresql.conf``
RUN echo "listen_addresses='*'" >> /var/lib/pgsql/9.4/data/postgresql.conf

# Run the rest of the commands as the ``postgres`` user created by the ``postgresql94-server`` 
# package when it was ``yum installed``
USER postgres

# Create a PostgreSQL role named ``docker`` with ``docker`` as the password and
# then create a database `docker` owned by the ``docker`` role.
# After start, sleep for 5 secs to make sure that postmaster is started before
# creating the role and database:
RUN  /usr/pgsql-9.4/bin/pg_ctl -D /var/lib/pgsql/9.4/data start &&\
    sleep 5 &&\
    psql --command "CREATE USER docker WITH SUPERUSER PASSWORD 'docker';" &&\
    createdb -O docker docker

# Expose the PostgreSQL port
EXPOSE 5432

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME  ["/var/lib/pgsql/9.4"]

# Set the default command to run when starting the container
CMD ["/usr/pgsql-9.4/bin/postgres", "-D", "/var/lib/pgsql/9.4/data"]
