#################################
# Makefile for PostgreSQL 16	#
# testing packaging	 	#
# https://yum.postgresql.org	#
#			   	#
# Devrim Gunduz		   	#
# devrim@gunduz.org	   	#
#################################
#			 	#
#				#
# build target is for      	#
# RPM buildfarm		   	#
#			   	#
#			   	#
#################################


## PostgreSQL 16 Testing

build16testing: prep16
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm16testing/BUILDROOT" \
	--define "_builddir $(HOME)/rpm16testing/BUILD" \
	--define "_srcrpmdir $(HOME)/rpm16testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm16testing/RPMS/" \
	--define "pgmajorversion 16" --define "pginstdir /usr/pgsql-16" --define "pgpackageversion 16" \
	--define "dist $(DIST)" -bb $(SPECFILE)
	make bfsrpm16testing

srpm16testing: prep16
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir ." \
	--define "_buildrootdir $(HOME)/rpm16testing/BUILDROOT" \
	--define "pgmajorversion 16" --define "pginstdir /usr/pgsql-16"  --define "pgpackageversion 16" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

bfsrpm16testing: prep16
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm16testing/SRPMS" \
	--define "_buildrootdir $(HOME)/rpm16testing/BUILDROOT" \
	--define "pgmajorversion 16" --define "pginstdir /usr/pgsql-16"  --define "pgpackageversion 16" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

bfnosignsrpm16testing: prep16
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_buildrootdir $(HOME)/rpm16testing/BUILDROOT" \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm16testing/SRPMS" \
	--define "pgmajorversion 16" --define "pginstdir /usr/pgsql-16"  --define "pgpackageversion 16" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

rpm16testing: prep16
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm16testing/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 16" --define "pginstdir /usr/pgsql-16" --define "pgpackageversion 16" \
	--define "dist $(DIST)" -bb $(SPECFILE)

nosignbuild16testimg:
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(HOME)/rpm16testing/BUILD" \
	--define "_buildrootdir $(HOME)/rpm16testing/BUILDROOT" \
	--define "_srcrpmdir $(HOME)/rpm16testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm16testing/RPMS/" \
	--define "pgmajorversion 16" --define "pginstdir /usr/pgsql-16" --define "pgpackageversion 16" \
	--define "dist $(DIST)" -bb $(SPECFILE)
	make bfnosignsrpm16testing

noprepbuild16testing:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm16testing/SRPMS" \
	--define "_buildrootdir $(HOME)/rpm16testing/BUILDROOT" \
	--define "pgmajorversion 16" --define "pginstdir /usr/pgsql-16" --define "pgpackageversion 16" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(HOME)/rpm16testing/BUILD" \
	--define "_buildrootdir $(HOME)/rpm16testing/BUILDROOT" \
	--define "_srcrpmdir $(HOME)/rpm16testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm16testing/RPMS/" \
	--define "pgmajorversion 16" --define "pginstdir /usr/pgsql-16" --define "pgpackageversion 16" \
	--define "dist $(DIST)" -bb $(SPECFILE)

nopreprpm16testing:
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm16testing/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 16" --define "pginstdir /usr/pgsql-16" --define "pgpackageversion 16" \
	--define "dist $(DIST)" -bb $(SPECFILE)

noprepsrpm16testing:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir ." \
	--define "_buildrootdir $(HOME)/rpm16testing/BUILDROOT" \
	--define "pgmajorversion 16" --define "pginstdir /usr/pgsql-16" --define "pgpackageversion 16" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)
