#################################
# Makefile for PostgreSQL 13	#
# testing packaging	 	#
# https://yum.postgresql.org	#
#			   	#
# Devrim Gunduz		   	#
# devrim@gunduz.org	   	#
#################################
#			 	#
#				#
# build target is for      	#
# RPM buildfarm		   	#
#			   	#
#			   	#
#################################


## PostgreSQL 13 Testing

build13testing: prep13
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm13testing/BUILDROOT" \
	--define "_builddir $(HOME)/rpm13testing/BUILD" \
	--define "_srcrpmdir $(HOME)/rpm13testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm13testing/RPMS/" \
	--define "pgmajorversion 13" --define "pginstdir /usr/pgsql-13" --define "pgpackageversion 13" \
	--define "dist $(DIST)" -bb $(SPECFILE)
	make bfsrpm13testing

srpm13testing: prep13
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir ." \
	--define "_buildrootdir $(HOME)/rpm13testing/BUILDROOT" \
	--define "pgmajorversion 13" --define "pginstdir /usr/pgsql-13"  --define "pgpackageversion 13" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

bfsrpm13testing: prep13
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm13testing/SRPMS" \
	--define "_buildrootdir $(HOME)/rpm13testing/BUILDROOT" \
	--define "pgmajorversion 13" --define "pginstdir /usr/pgsql-13"  --define "pgpackageversion 13" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

bfnosignsrpm13testing: prep13
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_buildrootdir $(HOME)/rpm13testing/BUILDROOT" \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm13testing/SRPMS" \
	--define "pgmajorversion 13" --define "pginstdir /usr/pgsql-13"  --define "pgpackageversion 13" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

rpm13testing: prep13
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm13testing/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 13" --define "pginstdir /usr/pgsql-13" --define "pgpackageversion 13" \
	--define "dist $(DIST)" -bb $(SPECFILE)

nosignbuild13testimg:
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(HOME)/rpm13testing/BUILD" \
	--define "_buildrootdir $(HOME)/rpm13testing/BUILDROOT" \
	--define "_srcrpmdir $(HOME)/rpm13testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm13testing/RPMS/" \
	--define "pgmajorversion 13" --define "pginstdir /usr/pgsql-13" --define "pgpackageversion 13" \
	--define "dist $(DIST)" -bb $(SPECFILE)
	make bfnosignsrpm13testing

noprepbuild13testing:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm13testing/SRPMS" \
	--define "_buildrootdir $(HOME)/rpm13testing/BUILDROOT" \
	--define "pgmajorversion 13" --define "pginstdir /usr/pgsql-13" --define "pgpackageversion 13" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(HOME)/rpm13testing/BUILD" \
	--define "_buildrootdir $(HOME)/rpm13testing/BUILDROOT" \
	--define "_srcrpmdir $(HOME)/rpm13testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm13testing/RPMS/" \
	--define "pgmajorversion 13" --define "pginstdir /usr/pgsql-13" --define "pgpackageversion 13" \
	--define "dist $(DIST)" -bb $(SPECFILE)

nopreprpm13testing:
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm13testing/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 13" --define "pginstdir /usr/pgsql-13" --define "pgpackageversion 13" \
	--define "dist $(DIST)" -bb $(SPECFILE)

noprepsrpm13testing:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir ." \
	--define "_buildrootdir $(HOME)/rpm13testing/BUILDROOT" \
	--define "pgmajorversion 13" --define "pginstdir /usr/pgsql-13" --define "pgpackageversion 13" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)
