#################################
# Makefile for PostgreSQL 18	#
# testing packaging		#
# https://yum.postgresql.org	#
#				#
# Devrim Gunduz			#
# devrim@gunduz.org		#
#################################
#				#
#				#
# build target is for		#
# RPM buildfarm			#
#				#
#				#
#################################


## PostgreSQL 18 Testing

build18testing: prep18
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm18testing/BUILDROOT" \
	--define "_builddir $(HOME)/rpm18testing/BUILD" \
	--define "_srcrpmdir $(HOME)/rpm18testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm18testing/RPMS/" \
	--define "pgmajorversion 18" --define "pginstdir /usr/pgsql-18" --define "pgpackageversion 18" \
	-bb $(SPECFILE)
	make bfsrpm18testing

srpm18testing: prep18
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir ." \
	--define "_buildrootdir $(HOME)/rpm18testing/BUILDROOT" \
	--define "pgmajorversion 18" --define "pginstdir /usr/pgsql-18" --define "pgpackageversion 18" \
	--define "_rpmdir ." --nodeps -bs $(SPECFILE)

bfsrpm18testing: prep18
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm18testing/SRPMS" \
	--define "_buildrootdir $(HOME)/rpm18testing/BUILDROOT" \
	--define "pgmajorversion 18" --define "pginstdir /usr/pgsql-18" --define "pgpackageversion 18" \
	--define "_rpmdir ." --nodeps -bs $(SPECFILE)

bfnoprepsrpm18testing:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm18testing/SRPMS" \
	--define "_buildrootdir $(HOME)/rpm18testing/BUILDROOT" \
	--define "pgmajorversion 18" --define "pginstdir /usr/pgsql-18" --define "pgpackageversion 18" \
	--define "_rpmdir ." --nodeps -bs $(SPECFILE)

bfnosignsrpm18testing: prep18
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_buildrootdir $(HOME)/rpm18testing/BUILDROOT" \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm18testing/SRPMS" \
	--define "pgmajorversion 18" --define "pginstdir /usr/pgsql-18" --define "pgpackageversion 18" \
	--define "_rpmdir ." --nodeps -bs $(SPECFILE)

rpm18testing: prep18
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm18testing/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 18" --define "pginstdir /usr/pgsql-18" --define "pgpackageversion 18" \
	-bb $(SPECFILE)

nosignbuild18testimg:
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define "_builddir $(HOME)/rpm18testing/BUILD" \
	--define "_buildrootdir $(HOME)/rpm18testing/BUILDROOT" \
	--define "_srcrpmdir $(HOME)/rpm18testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm18testing/RPMS/" \
	--define "pgmajorversion 18" --define "pginstdir /usr/pgsql-18" --define "pgpackageversion 18" \
	-bb $(SPECFILE)
	make bfnosignsrpm18testing

noprepbuild18testing:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm18testing/SRPMS" \
	--define "_buildrootdir $(HOME)/rpm18testing/BUILDROOT" \
	--define "pgmajorversion 18" --define "pginstdir /usr/pgsql-18" --define "pgpackageversion 18" \
	--define "_rpmdir ." --nodeps -bs $(SPECFILE)

	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define "_builddir $(HOME)/rpm18testing/BUILD" \
	--define "_buildrootdir $(HOME)/rpm18testing/BUILDROOT" \
	--define "_srcrpmdir $(HOME)/rpm18testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm18testing/RPMS/" \
	--define "pgmajorversion 18" --define "pginstdir /usr/pgsql-18" --define "pgpackageversion 18" \
	-bb $(SPECFILE)

nopreprpm18testing:
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm18testing/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 18" --define "pginstdir /usr/pgsql-18" --define "pgpackageversion 18" \
	-bb $(SPECFILE)

noprepsrpm18testing:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir ." \
	--define "_buildrootdir $(HOME)/rpm18testing/BUILDROOT" \
	--define "pgmajorversion 18" --define "pginstdir /usr/pgsql-18" --define "pgpackageversion 18" \
	--define "_rpmdir ." --nodeps -bs $(SPECFILE)
