#################################
# Makefile for PostgreSQL 	#
# Extras packaging	 	#
# https://yum.postgresql.org	#
#			   	#
# Devrim Gunduz		   	#
# devrim@gunduz.org	   	#
#################################

## PostgreSQL extras build targets

extrasbfsrpmtesting: prep
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/pgdg$(DIST).extrastesting/SRPMS" \
	--define "_buildrootdir $(HOME)/pgdg$(DIST).extrastesting/BUILDROOT" \
	--define "pgmajorversion 17" --define "pginstdir /usr/pgsql-17"  --define "pgpackageversion 17" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

extrasbuildtesting: prep
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define "_buildrootdir $(HOME)/pgdg$(DIST).extrastesting/BUILDROOT" \
	--define "_builddir $(HOME)/pgdg$(DIST).extrastesting/BUILD" \
	--define "_srcrpmdir $(HOME)/pgdg$(DIST).extrastesting/SRPMS" \
	--define "_rpmdir $(HOME)/pgdg$(DIST).extrastesting/RPMS/" \
	--define "pgmajorversion 17" --define "pginstdir /usr/pgsql-17" --define "pgpackageversion 17" \
	--define "dist $(DIST)" -bb $(SPECFILE)
	make extrasbfsrpm

extrasrpmtesting: prep
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/pgdg$(DIST).extrastesting/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 17" --define "pginstdir /usr/pgsql-17" --define "pgpackageversion 17" \
	--define "dist $(DIST)" -bb $(SPECFILE)

extrasnoprepbuildtesting:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/pgdg$(DIST).extrastesting/SRPMS" \
	--define "_buildrootdir $(HOME)/pgdg$(DIST).extrastesting/BUILDROOT" \
	--define "pgmajorversion 17" --define "pginstdir /usr/pgsql-17" --define "pgpackageversion 17" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(HOME)/pgdg$(DIST).extrastesting/BUILD" \
	--define "_buildrootdir $(HOME)/pgdg$(DIST).extrastesting/BUILDROOT" \
	--define "_srcrpmdir $(HOME)/pgdg$(DIST).extrastesting/SRPMS" \
	--define "_rpmdir $(HOME)/pgdg$(DIST).extrastesting/RPMS/" \
	--define "pgmajorversion 17" --define "pginstdir /usr/pgsql-17" --define "pgpackageversion 17" \
	--define "dist $(DIST)" -bb $(SPECFILE)

extrasnopreprpmtesting:
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/pgdg$(DIST).extrastesting/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 17" --define "pginstdir /usr/pgsql-17" --define "pgpackageversion 17" \
	--define "dist $(DIST)" -bb $(SPECFILE)

extrasnoprepsrpmtesting:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir ." \
	--define "_buildrootdir $(HOME)/pgdg$(DIST).extrastesting/BUILDROOT" \
	--define "pgmajorversion 17" --define "pginstdir /usr/pgsql-17" --define "pgpackageversion 17" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

