#################################
# Makefile for PostgreSQL 12	#
# testing packaging	 	#
# https://yum.postgresql.org	#
#			   	#
# Devrim Gunduz		   	#
# devrim@gunduz.org	   	#
#################################
#			 	#
#				#
# build target is for      	#
# RPM buildfarm		   	#
#			   	#
#			   	#
#################################


## PostgreSQL 12 Testing

build12testing: bfsrpm12testing
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm12testing/BUILDROOT" \
	--define "_builddir $(HOME)/rpm12testing/BUILD" \
	--define "_srcrpmdir $(HOME)/rpm12testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm12testing/RPMS/" \
	--define "pgmajorversion 12" --define "pginstdir /usr/pgsql-12" --define "pgpackageversion 12" \
	--define "dist $(DIST)" -bb $(SPECFILE)

srpm12testing: prep12
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir ." \
	--define "_buildrootdir $(HOME)/rpm12testing/BUILDROOT" \
	--define "pgmajorversion 12" --define "pginstdir /usr/pgsql-12"  --define "pgpackageversion 12" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

bfsrpm12testing: prep12
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm12testing/SRPMS" \
	--define "_buildrootdir $(HOME)/rpm12testing/BUILDROOT" \
	--define "pgmajorversion 12" --define "pginstdir /usr/pgsql-12"  --define "pgpackageversion 12" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

bfnosignsrpm12testing: prep12
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_buildrootdir $(HOME)/rpm12testing/BUILDROOT" \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm12testing/SRPMS" \
	--define "pgmajorversion 12" --define "pginstdir /usr/pgsql-12"  --define "pgpackageversion 12" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

rpm12testing: prep12
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm12testing/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 12" --define "pginstdir /usr/pgsql-12" --define "pgpackageversion 12" \
	--define "dist $(DIST)" -bb $(SPECFILE)

nosignbuild12testimg: bfnosignsrpm12testing
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(HOME)/rpm12testing/BUILD" \
	--define "_buildrootdir $(HOME)/rpm12testing/BUILDROOT" \
	--define "_srcrpmdir $(HOME)/rpm12testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm12testing/RPMS/" \
	--define "pgmajorversion 12" --define "pginstdir /usr/pgsql-12" --define "pgpackageversion 12" \
	--define "dist $(DIST)" -bb $(SPECFILE)

noprepbuild12testing:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm12testing/SRPMS" \
	--define "_buildrootdir $(HOME)/rpm12testing/BUILDROOT" \
	--define "pgmajorversion 12" --define "pginstdir /usr/pgsql-12" --define "pgpackageversion 12" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(HOME)/rpm12testing/BUILD" \
	--define "_buildrootdir $(HOME)/rpm12testing/BUILDROOT" \
	--define "_srcrpmdir $(HOME)/rpm12testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm12testing/RPMS/" \
	--define "pgmajorversion 12" --define "pginstdir /usr/pgsql-12" --define "pgpackageversion 12" \
	--define "dist $(DIST)" -bb $(SPECFILE)

nopreprpm12testing:
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm12testing/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 12" --define "pginstdir /usr/pgsql-12" --define "pgpackageversion 12" \
	--define "dist $(DIST)" -bb $(SPECFILE)

noprepsrpm12testing:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir ." \
	--define "_buildrootdir $(HOME)/rpm12testing/BUILDROOT" \
	--define "pgmajorversion 12" --define "pginstdir /usr/pgsql-12" --define "pgpackageversion 12" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)
