################################
# RPM-specific Makefile        #
# http://yum.postgresql.org    #
#                              #
# Devrim Gunduz                #
# devrim@gunduz.org            #
################################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.f17
SPECFILE="postgres-xc-1.0.spec"
HOMEDIR=$HOMEDIR

# Now, include global Makefile
include ../../../common/Makefile.global
