#################################
# RPM-specific Makefile		#
# https://yum.postgresql.org	#
#				#
# Devrim Gunduz			#
# devrim@gunduz.org		#
#################################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.f34
SPECFILE="ldap2pg.spec"

# Now, include global Makefile
include ../../../../global/Makefile.global
