#################################
# RPM-specific Makefile		#
# https://yum.postgresql.org	#
#                         	#
# Devrim Gunduz           	#
# devrim@gunduz.org        	#
#################################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.f34
SPECFILE="gdal32.spec"

# Now, include global Makefile
include ../../../../global/Makefile.global
